In [2]:
import pandas as pd
import numpy as np

In [3]:
data = {
    'Name' : ['James Ogah', 'Samuel jin', 'kristof ole', 'John brown', 'benedict patrick',
             'folarin Balogun'],
    'Gender' : ['male', 'Female', 'FEMALE', 'm', 'MALE', ' male'],
    
    'Age' : [20, 21, 30, 'nine', 20, 15],
    'Salary' : [100, 300, 800, 900, 500, 'one'],
    'Performance_Score' : [20, 15, 10, np.nan, 12, 200]   
}

In [75]:
df = pd.DataFrame(data)
print(df)

               Name  Gender   Age Salary  Performance_Score
0        James Ogah    male    20    100               20.0
1        Samuel jin  Female    21    300               15.0
2       kristof ole  FEMALE    30    800               10.0
3        John brown       m  nine    900                NaN
4  benedict patrick    MALE    20    500               12.0
5   folarin Balogun    male    15    one              200.0

In [76]:
df.shape

(6, 5)

In [24]:
df.describe()

       Performance_Score
count           5.000000
mean           51.400000
std            83.155276
min            10.000000
25%            12.000000
50%            15.000000
75%            20.000000
max           200.000000

In [25]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Name               6 non-null      str
 1   Gender             6 non-null      str
 2   Age                6 non-null      object
 3   Salary             6 non-null      object
 4   Performance_Score  5 non-null      float64
dtypes: float64(1), object(2), str(2)
memory usage: 470.0+ bytes

In [26]:
#Fixing Numerical columns
#Fixing Age
#Checking the age

df['Age'].dtype

dtype('O')

In [77]:
df['Age']

0      20
1      21
2      30
3    nine
4      20
5      15
Name: Age, dtype: object

In [28]:
#Identifying the problematic row
df[pd.to_numeric(df['Age'], errors = 'coerce'). isna()]

         Name Gender   Age Salary  Performance_Score
3  John brown      m  nine    900                NaN

In [30]:
#fixing the problematic rows by inserting the values or changing them to a missing value
df['Age'] = df['Age'].replace({
    'nine' : 9
})
df['Age']

0    20
1    21
2    30
3     9
4    20
5    15
Name: Age, dtype: object

In [78]:
#or
#By changing the value to a null value
df.loc[3, 'Age'] = np.nan
df['Age']

0     20
1     21
2     30
3    NaN
4     20
5     15
Name: Age, dtype: object

In [33]:
#Check the datatype if it is in numerical datatype
df['Age'].dtype

dtype('O')

In [35]:
#If its not change it to a numerical datatype
df['Age'] = pd.to_numeric(df['Age'], errors = 'coerce')
df['Age']

0    20.0
1    21.0
2    30.0
3     NaN
4    20.0
5    15.0
Name: Age, dtype: float64

In [60]:
#Also check for missing values
df['Age'].isnull().sum()

np.int64(0)

In [37]:
#Search for outliers before inserting the missing values
#Age outliers
Q1 = df['Age'].quantile(0.25)
Q3 = df['Age'].quantile(0.75)

IQR = Q3 - Q1
print(IQR)

1.0

In [43]:
lower_limit = Q1 - 1.5 * IQR
higher_limit = Q3 + 1.5 * IQR

print(lower_limit , higher_limit)

18.5 22.5

In [50]:
#To inspect the outliers
for index, row in df.iterrows():
        if(row['Age'] < lower_limit or row['Age'] > higher_limit):
            print(row)

Name                 kristof ole
Gender                    FEMALE
Age                         30.0
Salary                       800
Performance_Score           10.0
Name: 2, dtype: object
Name                 folarin Balogun
Gender                          male
Age                             15.0
Salary                           one
Performance_Score              200.0
Name: 5, dtype: object

In [42]:
#Decide whether to us the mean,median or mode in a column
Agemean = df['Age'].mean()
Agemedian = df['Age'].median()
Agemode = df['Age'].mode()
print(Agemean)
print(Agemedian)
print(Agemode)

21.2
20.0
0    20.0
Name: Age, dtype: float64

In [53]:
#When the outliers are inspected and handled and the rest prove to be bad data there can be corrected with these conditions
#We will use median
df.loc[df['Age'] < lower_limit, 'Age'] = Agemedian
df.loc[df['Age'] > higher_limit, 'Age'] = Agemedian

In [74]:
df

               Name  Gender  Age Salary  Performance_Score
0        James Ogah    male    0    100               20.0
1        Samuel jin  Female    0    300               15.0
2       kristof ole  FEMALE    0    800               10.0
3        John brown       m    0    900                NaN
4  benedict patrick    MALE    0    500               12.0
5   folarin Balogun    male    0    one              200.0

In [82]:
#Then fill missing values
df['Age'] = df['Age'].fillna(Agemedian)

In [83]:
df

               Name  Gender   Age Salary  Performance_Score
0        James Ogah    male    20    100               20.0
1        Samuel jin  Female    21    300               15.0
2       kristof ole  FEMALE    30    800               10.0
3        John brown       m  20.0    900                NaN
4  benedict patrick    MALE    20    500               12.0
5   folarin Balogun    male    15    one              200.0

In [62]:
#Now for Salary
df['Salary'].isnull().sum()

np.int64(0)

In [63]:
df['Salary'].dtype

dtype('O')

In [80]:
df[pd.to_numeric(df['Salary'], errors = 'coerce'). isna()]

              Name Gender Age Salary  Performance_Score
5  folarin Balogun   male  15    one              200.0

In [85]:
df['Salary'] = pd.to_numeric(df['Salary'], errors = 'coerce')

In [86]:
df

               Name  Gender   Age  Salary  Performance_Score
0        James Ogah    male    20   100.0               20.0
1        Samuel jin  Female    21   300.0               15.0
2       kristof ole  FEMALE    30   800.0               10.0
3        John brown       m  20.0   900.0                NaN
4  benedict patrick    MALE    20   500.0               12.0
5   folarin Balogun    male    15     NaN              200.0

In [87]:
#Outliers for salary
Q1 = df['Salary'].quantile(0.25)
Q3 = df['Salary'].quantile(0.75)

IQR = Q3 - Q1
print(IQR)

500.0

In [88]:
lower_limit = Q1 - 1.5 * IQR
higher_limit = Q3 + 1.5 * IQR

print(lower_limit, higher_limit)

-450.0 1550.0

In [102]:
for index, row in df.iterrows():
    if (row['Salary'] < lower_limit or row['Salary'] > higher_limit):
        print(row)

In [103]:
salarymedian = df['Salary'].median()
salarymean = df['Salary'].mean()
print(salarymedian)
print(salarymean)

500.0
520.0

In [107]:
df['Salary'].fillna(salarymean)

0    100.0
1    300.0
2    800.0
3    900.0
4    500.0
5    520.0
Name: Salary, dtype: float64

In [109]:
df['Salary']

0    100.0
1    300.0
2    800.0
3    900.0
4    500.0
5      NaN
Name: Salary, dtype: float64

In [112]:
df['Salary'] = df['Salary'].fillna(salarymean)

In [113]:
df

               Name  Gender   Age  Salary  Performance_Score
0        James Ogah    male    20   100.0               20.0
1        Samuel jin  Female    21   300.0               15.0
2       kristof ole  FEMALE    30   800.0               10.0
3        John brown       m  20.0   900.0                NaN
4  benedict patrick    MALE    20   500.0               12.0
5   folarin Balogun    male    15   520.0              200.0

In [116]:
#Outlier for Performance_Score
Q1 = df['Performance_Score'].quantile(0.25)
Q3 = df['Performance_Score']. quantile(0.75)

IQR = Q3 - Q1
print(IQR)

8.0

In [117]:
lower_limit = Q1 - 1.5 * IQR
higher_limit = Q3 + 1.5 * IQR

print(lower_limit, higher_limit)

0.0 32.0

In [118]:
 for index, row in df.iterrows():
    if (row['Performance_Score'] < lower_limit or row['Performance_Score'] > higher_limit):
        print(row)

Name                 folarin Balogun
Gender                          male
Age                               15
Salary                         520.0
Performance_Score              200.0
Name: 5, dtype: object

In [120]:
df.loc[df['Performance_Score'] < lower_limit, 'Performance_Score'] = np.nan
df.loc[df['Performance_Score'] > higher_limit, 'Performance_Score'] = np.nan

In [124]:
df['Performance_Score']

0    20.0
1    15.0
2    10.0
3     NaN
4    12.0
5     NaN
Name: Performance_Score, dtype: float64

In [126]:
pmean = df['Performance_Score'].mean()
pmedian = df['Performance_Score'].median()
print(pmean)
print(pmedian)

14.25
13.5

In [127]:
df['Performance_Score'] = df['Performance_Score'].fillna(pmedian)

In [128]:
df

               Name  Gender   Age  Salary  Performance_Score
0        James Ogah    male    20   100.0               20.0
1        Samuel jin  Female    21   300.0               15.0
2       kristof ole  FEMALE    30   800.0               10.0
3        John brown       m  20.0   900.0               13.5
4  benedict patrick    MALE    20   500.0               12.0
5   folarin Balogun    male    15   520.0               13.5

In [131]:
df['Age'] = pd.to_numeric(df['Age'], errors = 'coerce')

In [132]:
df

               Name  Gender  Age  Salary  Performance_Score
0        James Ogah    male   20   100.0               20.0
1        Samuel jin  Female   21   300.0               15.0
2       kristof ole  FEMALE   30   800.0               10.0
3        John brown       m   20   900.0               13.5
4  benedict patrick    MALE   20   500.0               12.0
5   folarin Balogun    male   15   520.0               13.5

In [215]:
#Excercise on cleaning numerical columns

Data = {
    'First Name':['john', 'JOSEPH', 'James', 'Jonah', 'Jack', 'Jim', 'kevin', 'Mel', 'Mel'],
    'Last Name' : ['Ogah', 'gaius', 'Mathew', 'Luke', 'Daniels', 'Halpert', 'Danso','Gibbins', 'Gibbins'],
    'Age' : ['20', 'twenty five', 25, 31, np.nan, 27, 31, 90, 90],
    'Performance_Score' : [20, 30, 10, 40, np.nan, 15, 'two', 80, 80]
}

In [216]:
df = pd.DataFrame(Data)
print(df)

  First Name Last Name          Age Performance_Score
0       john      Ogah           20                20
1     JOSEPH     gaius  twenty five                30
2      James    Mathew           25                10
3      Jonah      Luke           31                40
4       Jack   Daniels          NaN               NaN
5        Jim   Halpert           27                15
6      kevin     Danso           31               two
7        Mel   Gibbins           90                80
8        Mel   Gibbins           90                80

In [217]:
df.head()

  First Name Last Name          Age Performance_Score
0       john      Ogah           20                20
1     JOSEPH     gaius  twenty five                30
2      James    Mathew           25                10
3      Jonah      Luke           31                40
4       Jack   Daniels          NaN               NaN

In [218]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 4 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   First Name         9 non-null      str
 1   Last Name          9 non-null      str
 2   Age                8 non-null      object
 3   Performance_Score  8 non-null      object
dtypes: object(2), str(2)
memory usage: 510.0+ bytes

In [219]:
df.isnull().sum()

First Name           0
Last Name            0
Age                  1
Performance_Score    1
dtype: int64

In [220]:
df.isnull().sum().sum()

np.int64(2)

In [221]:
df.duplicated().sum()

np.int64(1)

In [222]:
print(df[df.duplicated(keep = False)])

  First Name Last Name Age Performance_Score
7        Mel   Gibbins  90                80
8        Mel   Gibbins  90                80

In [223]:
df = df.drop_duplicates()

In [224]:
df.duplicated().sum()

np.int64(0)

In [225]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 4 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   First Name         8 non-null      str
 1   Last Name          8 non-null      str
 2   Age                7 non-null      object
 3   Performance_Score  7 non-null      object
dtypes: object(2), str(2)
memory usage: 470.0+ bytes

In [226]:
df['Age'].dtype

dtype('O')

In [227]:
df[pd.to_numeric(df['Age'], errors = 'coerce').isna()]

  First Name Last Name          Age Performance_Score
1     JOSEPH     gaius  twenty five                30
4       Jack   Daniels          NaN               NaN

In [228]:
df['Age'] = df['Age'].replace({
    'twenty five' : 25
})

In [229]:
df['Age']

0     20
1     25
2     25
3     31
4    NaN
5     27
6     31
7     90
Name: Age, dtype: object

In [230]:
df['Age'] = pd.to_numeric(df['Age'], errors = 'coerce')

In [231]:
df['Age'].dtype

dtype('float64')

In [232]:
df['Age']

0    20.0
1    25.0
2    25.0
3    31.0
4     NaN
5    27.0
6    31.0
7    90.0
Name: Age, dtype: float64

In [233]:
agemean = df['Age'].mean()
agemedian = df['Age'].median()

print(agemean)
print(agemedian)

35.57142857142857
27.0

In [234]:
#Outliers for age
Q1 = df['Age'].quantile(0.25)
Q3 = df['Age'].quantile(0.75)

IQR = Q3 - Q1
print(IQR)

6.0

In [235]:
lower_limit = Q1 - 1.5 * IQR
higher_limit = Q3 + 1.5 * IQR

print(lower_limit, higher_limit)

16.0 40.0

In [236]:
for index, row in df.iterrows():
    if (row['Age'] < lower_limit or row['Age'] > higher_limit):
        print (row)

First Name               Mel
Last Name            Gibbins
Age                     90.0
Performance_Score         80
Name: 7, dtype: object

In [237]:
df.loc[df['Age'] > higher_limit, 'Age'] = np.nan

In [238]:
df['Age']

0    20.0
1    25.0
2    25.0
3    31.0
4     NaN
5    27.0
6    31.0
7     NaN
Name: Age, dtype: float64

In [239]:
df['Age'] = df['Age'].fillna(agemedian)

In [240]:
df['Age']

0    20.0
1    25.0
2    25.0
3    31.0
4    27.0
5    27.0
6    31.0
7    27.0
Name: Age, dtype: float64

In [241]:
df.columns

Index(['First Name', 'Last Name', 'Age', 'Performance_Score'], dtype='str')

In [244]:
df['Performance_Score'].dtype

dtype('O')

In [246]:
df[pd.to_numeric(df['Performance_Score'], errors = 'coerce').isna()]

  First Name Last Name   Age Performance_Score
4       Jack   Daniels  27.0               NaN
6      kevin     Danso  31.0               two

In [248]:
df['Performance_Score'] = pd.to_numeric(df['Performance_Score'], errors = 'coerce')

In [249]:
df['Performance_Score'].dtype

dtype('float64')

In [250]:
df['Performance_Score']

0    20.0
1    30.0
2    10.0
3    40.0
4     NaN
5    15.0
6     NaN
7    80.0
Name: Performance_Score, dtype: float64

In [260]:
#Outliers
#creating a function to find outliers
def find_outlier (df, column):
    Q1 = df[column].quantile(0.25)
    Q3 = df[column].quantile(0.75)

    IQR = Q3 - Q1

    lower_limit = Q1 - 1.5 * IQR
    higher_limit = Q3 + 1.5 * IQR

    return lower_limit, higher_limit

In [266]:
print(df['Performance_Score'].median())

20.0

In [261]:
outlier = find_outlier(df, 'Performance_Score')
print (outlier)

(np.float64(-15.625), np.float64(69.375))

In [263]:
for index, row in df.iterrows():
    if (row['Performance_Score'] < lower_limit or  row['Performance_Score'] > higher_limit):
        print(row)

First Name               Mel
Last Name            Gibbins
Age                     27.0
Performance_Score       80.0
Name: 7, dtype: object

In [264]:
df.loc[df['Performance_Score'] > higher_limit, 'Performance_Score'] = np.nan

In [267]:
df['Performance_Score'] = df['Performance_Score'].fillna(df['Performance_Score'].median())

In [268]:
df['Performance_Score']

0    20.0
1    30.0
2    10.0
3    40.0
4    20.0
5    15.0
6    20.0
7    20.0
Name: Performance_Score, dtype: float64

In [269]:
#Completely filled numerical columns
df

  First Name Last Name   Age  Performance_Score
0       john      Ogah  20.0               20.0
1     JOSEPH     gaius  25.0               30.0
2      James    Mathew  25.0               10.0
3      Jonah      Luke  31.0               40.0
4       Jack   Daniels  27.0               20.0
5        Jim   Halpert  27.0               15.0
6      kevin     Danso  31.0               20.0
7        Mel   Gibbins  27.0               20.0

In [271]:
Performance_remark = []
for score in df['Performance_Score']:
    if score < 10:
        Performance_remark.append('Very poor')
    elif score < 20:
        Performance_remark.append('Poor')
    elif score < 30:
        Performance_remark.append('Good')
    elif score < 40:
        Performance_remark.append('Very Good')
    elif score < 50:
        Performance_remark.append('Excellent')
        
df['Performance_remark'] = Performance_remark

In [272]:
df

  First Name Last Name   Age  Performance_Score Performance_remark
0       john      Ogah  20.0               20.0               Good
1     JOSEPH     gaius  25.0               30.0          Very Good
2      James    Mathew  25.0               10.0               Poor
3      Jonah      Luke  31.0               40.0          Excellent
4       Jack   Daniels  27.0               20.0               Good
5        Jim   Halpert  27.0               15.0               Poor
6      kevin     Danso  31.0               20.0               Good
7        Mel   Gibbins  27.0               20.0               Good