In [1]:
import pandas as pd
import numpy as np

In [2]:
data = np.array([
    [101, "John Smith", 24, "Male", 45000, "Lagos", "12/01/2023"],
    [102, "Mary Jones", 27, "Female", 52000, "Abuja", "25/02/2023"],
    [103, "David Brown", 31, "Male", 68000, "Kaduna", "10/03/2023"],
    [104, "Sarah Wilson", 29, "Female", 59000, "lagos", "15/03/2023"],
    [105, "Michael Lee", 35, "Male", 75000, "Abuja", "01/04/2023"],
    [106, "Grace Taylor", 26, "Female", 48000, "KADUNA", "12/04/2023"],
    [107, "Daniel White", 42, "Male", 95000, "Lagos", "20/04/2023"],
    [108, "Jane Green", 30, "Female", 61000, "Abuja", "05/05/2023"],
    [109, "Peter Adams", 28, "Male", 55000, "Lagos", "18/05/2023"],
    [110, "Linda Clark", 33, "Female", 72000, "Kaduna", "25/05/2023"],
    [111, "Chris Evans", "unknown", "Male", 64000, "Lagos", "01/06/2023"],
    [112, "Anna Hall", 25, "Female", np.nan, "Abuja", "10/06/2023"],
    [113, "Robert King", 39, "Male", 88000, "Kaduna", "15/06/2023"],
    [114, "Mrs Emily Stone", 32, "Female", 67000, "Lagos", "30/06/2023"],
    [115, "Mark Young", 45, "Male", 250000, "Abuja", "05/07/2023"],
    [116, "Susan Wright", 29, "female", 58000, "Lagos", "12/07/2023"],
    [117, "James Scott", 34, "Male", 70000, "Kaduna", "20/07/2023"],
    [118, "Helen Baker", 27, "Female", 51000, "abuja", "28/07/2023"],
    [119, "Paul Nelson", 41, "Male", 91000, "Lagos", "05/08/2023"],
    [120, "Rachel Carter", 30, "Female", 63000, "Kaduna", "15/08/2023"],
    [120, "Rachel Carter", 30, "Female", 63000, "Kaduna", "15/08/2023"]
])

columns = [
    "Employee_ID",
    "Name",
    "Age",
    "Gender",
    "Salary",
    "City",
    "Join_Date"
]

In [6]:
dataframe = pd.DataFrame(data, columns = columns)

In [7]:
df = dataframe.copy()

In [8]:
df.head()

  Employee_ID          Name Age  Gender Salary    City   Join_Date
0         101    John Smith  24    Male  45000   Lagos  12/01/2023
1         102    Mary Jones  27  Female  52000   Abuja  25/02/2023
2         103   David Brown  31    Male  68000  Kaduna  10/03/2023
3         104  Sarah Wilson  29  Female  59000   lagos  15/03/2023
4         105   Michael Lee  35    Male  75000   Abuja  01/04/2023

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 21 entries, 0 to 20
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Employee_ID  21 non-null     str
 1   Name         21 non-null     str
 2   Age          21 non-null     str
 3   Gender       21 non-null     str
 4   Salary       21 non-null     str
 5   City         21 non-null     str
 6   Join_Date    21 non-null     str
dtypes: str(7)
memory usage: 2.1 KB

In [10]:
df.isnull().sum()

Employee_ID    0
Name           0
Age            0
Gender         0
Salary         0
City           0
Join_Date      0
dtype: int64

In [12]:
df.duplicated().sum()

np.int64(1)

In [14]:
df[df.duplicated(keep = False)]

   Employee_ID           Name Age  Gender Salary    City   Join_Date
19         120  Rachel Carter  30  Female  63000  Kaduna  15/08/2023
20         120  Rachel Carter  30  Female  63000  Kaduna  15/08/2023

In [15]:
df.drop_duplicates()

   Employee_ID             Name      Age  Gender  Salary    City   Join_Date
0          101       John Smith       24    Male   45000   Lagos  12/01/2023
1          102       Mary Jones       27  Female   52000   Abuja  25/02/2023
2          103      David Brown       31    Male   68000  Kaduna  10/03/2023
3          104     Sarah Wilson       29  Female   59000   lagos  15/03/2023
4          105      Michael Lee       35    Male   75000   Abuja  01/04/2023
5          106     Grace Taylor       26  Female   48000  KADUNA  12/04/2023
6          107     Daniel White       42    Male   95000   Lagos  20/04/2023
7          108       Jane Green       30  Female   61000   Abuja  05/05/2023
8          109      Peter Adams       28    Male   55000   Lagos  18/05/2023
9          110      Linda Clark       33  Female   72000  Kaduna  25/05/2023
10         111      Chris Evans  unknown    Male   64000   Lagos  01/06/2023
11         112        Anna Hall       25  Female     nan   Abuja  10/06/2023
12         113      Robert King       39    Male   88000  Kaduna  15/06/2023
13         114  Mrs Emily Stone       32  Female   67000   Lagos  30/06/2023
14         115       Mark Young       45    Male  250000   Abuja  05/07/2023
15         116     Susan Wright       29  female   58000   Lagos  12/07/2023
16         117      James Scott       34    Male   70000  Kaduna  20/07/2023
17         118      Helen Baker       27  Female   51000   abuja  28/07/2023
18         119      Paul Nelson       41    Male   91000   Lagos  05/08/2023
19         120    Rachel Carter       30  Female   63000  Kaduna  15/08/2023

In [16]:
df.shape

(21, 7)

In [18]:
df['Name'].unique()

<ArrowStringArray>
[     'John Smith',      'Mary Jones',     'David Brown',    'Sarah Wilson',
     'Michael Lee',    'Grace Taylor',    'Daniel White',      'Jane Green',
     'Peter Adams',     'Linda Clark',     'Chris Evans',       'Anna Hall',
     'Robert King', 'Mrs Emily Stone',      'Mark Young',    'Susan Wright',
     'James Scott',     'Helen Baker',     'Paul Nelson',   'Rachel Carter']
Length: 20, dtype: str

In [19]:
df[df['Name'] == 'Mrs']

Empty DataFrame
Columns: [Employee_ID, Name, Age, Gender, Salary, City, Join_Date]
Index: []

In [20]:
df['Name'] = df['Name'].replace({
    'Mrs Emily Stone' : 'Emily Stone'
})

In [21]:
df['Name'].unique()

<ArrowStringArray>
[   'John Smith',    'Mary Jones',   'David Brown',  'Sarah Wilson',
   'Michael Lee',  'Grace Taylor',  'Daniel White',    'Jane Green',
   'Peter Adams',   'Linda Clark',   'Chris Evans',     'Anna Hall',
   'Robert King',   'Emily Stone',    'Mark Young',  'Susan Wright',
   'James Scott',   'Helen Baker',   'Paul Nelson', 'Rachel Carter']
Length: 20, dtype: str

In [22]:
df[pd.to_numeric(df['Age'], errors = 'coerce').isna()]

   Employee_ID         Name      Age Gender Salary   City   Join_Date
10         111  Chris Evans  unknown   Male  64000  Lagos  01/06/2023

In [23]:
df['Age'] = pd.to_numeric(df['Age'], errors = 'coerce')

In [24]:
df['Age']

0     24.0
1     27.0
2     31.0
3     29.0
4     35.0
5     26.0
6     42.0
7     30.0
8     28.0
9     33.0
10     NaN
11    25.0
12    39.0
13    32.0
14    45.0
15    29.0
16    34.0
17    27.0
18    41.0
19    30.0
20    30.0
Name: Age, dtype: float64

In [25]:
#Outlier Function
def find_outlier(df, column):
    Q1 = df[column].quantile(0.25)
    Q3 = df[column].quantile(0.75)

    IQR = Q3 - Q1

    lowerlimit = Q1 - 1.5 * IQR
    higherlimit = Q3 + 1.5 * IQR

    return lowerlimit, higherlimit

In [26]:
#Age outlier
ageoutlier = find_outlier(df, 'Age')
print(ageoutlier)

(np.float64(18.0), np.float64(44.0))

In [27]:
agelowerlimit = 18.0
agehigherlimit = 44.0

for index, row in df.iterrows():
    if (row['Age'] < agelowerlimit or row['Age'] > agehigherlimit):
        print(row)

Employee_ID           115
Name           Mark Young
Age                  45.0
Gender               Male
Salary             250000
City                Abuja
Join_Date      05/07/2023
Name: 14, dtype: object

In [28]:
agemean = df['Age'].mean()
agemedian = df['Age'].median()
print(agemean)
print(agemedian)

31.85
30.0

In [29]:
df['Age'] = df['Age'].fillna(agemedian)

In [30]:
df.head()

  Employee_ID          Name   Age  Gender Salary    City   Join_Date
0         101    John Smith  24.0    Male  45000   Lagos  12/01/2023
1         102    Mary Jones  27.0  Female  52000   Abuja  25/02/2023
2         103   David Brown  31.0    Male  68000  Kaduna  10/03/2023
3         104  Sarah Wilson  29.0  Female  59000   lagos  15/03/2023
4         105   Michael Lee  35.0    Male  75000   Abuja  01/04/2023

In [31]:
df['Age'].info()

<class 'pandas.Series'>
RangeIndex: 21 entries, 0 to 20
Series name: Age
Non-Null Count  Dtype
--------------  -----
21 non-null     float64
dtypes: float64(1)
memory usage: 300.0 bytes

In [33]:
df['Gender'].unique()

<ArrowStringArray>
['Male', 'Female', 'female']
Length: 3, dtype: str

In [34]:
df['Gender'] = df['Gender'].replace({
    'female' : 'Female'
})

In [35]:
df['Gender'].unique()

<ArrowStringArray>
['Male', 'Female']
Length: 2, dtype: str

In [36]:
df['Salary'].info()

<class 'pandas.Series'>
RangeIndex: 21 entries, 0 to 20
Series name: Salary
Non-Null Count  Dtype
--------------  -----
21 non-null     str
dtypes: str(1)
memory usage: 404.0 bytes

In [38]:
df[pd.to_numeric(df['Salary'], errors = 'coerce').isna()]

   Employee_ID       Name   Age  Gender Salary   City   Join_Date
11         112  Anna Hall  25.0  Female    nan  Abuja  10/06/2023

In [39]:
df['Salary'] = pd.to_numeric(df['Salary'], errors = 'coerce')

In [40]:
salaryoutlier = find_outlier(df, 'Salary')
print(salaryoutlier)

(np.float64(34000.0), np.float64(96000.0))

In [41]:
slowerlimit = 34000.0
shigherlimit = 96000.0

for index, row in df.iterrows():
    if(row['Salary'] < slowerlimit or row['Salary'] > shigherlimit):
        print(row)

Employee_ID           115
Name           Mark Young
Age                  45.0
Gender               Male
Salary           250000.0
City                Abuja
Join_Date      05/07/2023
Name: 14, dtype: object

In [42]:
df['Salary']

0      45000.0
1      52000.0
2      68000.0
3      59000.0
4      75000.0
5      48000.0
6      95000.0
7      61000.0
8      55000.0
9      72000.0
10     64000.0
11         NaN
12     88000.0
13     67000.0
14    250000.0
15     58000.0
16     70000.0
17     51000.0
18     91000.0
19     63000.0
20     63000.0
Name: Salary, dtype: float64

In [44]:
salarymean = df['Salary'].mean()
salarymedian = df['Salary'].median()
print(salarymean)
print(salarymedian)

74750.0
63500.0

In [45]:
df['Salary'] = df['Salary'].fillna(salarymedian)

In [46]:
df.head()

  Employee_ID          Name   Age  Gender   Salary    City   Join_Date
0         101    John Smith  24.0    Male  45000.0   Lagos  12/01/2023
1         102    Mary Jones  27.0  Female  52000.0   Abuja  25/02/2023
2         103   David Brown  31.0    Male  68000.0  Kaduna  10/03/2023
3         104  Sarah Wilson  29.0  Female  59000.0   lagos  15/03/2023
4         105   Michael Lee  35.0    Male  75000.0   Abuja  01/04/2023

In [47]:
df['City'].unique()

<ArrowStringArray>
['Lagos', 'Abuja', 'Kaduna', 'lagos', 'KADUNA', 'abuja']
Length: 6, dtype: str

In [48]:
df['City'] = df['City'].str.lower()

In [50]:
df['City'] = df['City'].str.title()

In [51]:
df['City'].unique()

<ArrowStringArray>
['Lagos', 'Abuja', 'Kaduna']
Length: 3, dtype: str

In [52]:
df['Join_Date'].unique()

<ArrowStringArray>
['12/01/2023', '25/02/2023', '10/03/2023', '15/03/2023', '01/04/2023',
 '12/04/2023', '20/04/2023', '05/05/2023', '18/05/2023', '25/05/2023',
 '01/06/2023', '10/06/2023', '15/06/2023', '30/06/2023', '05/07/2023',
 '12/07/2023', '20/07/2023', '28/07/2023', '05/08/2023', '15/08/2023']
Length: 20, dtype: str

In [53]:
df

   Employee_ID           Name   Age  Gender    Salary    City   Join_Date
0          101     John Smith  24.0    Male   45000.0   Lagos  12/01/2023
1          102     Mary Jones  27.0  Female   52000.0   Abuja  25/02/2023
2          103    David Brown  31.0    Male   68000.0  Kaduna  10/03/2023
3          104   Sarah Wilson  29.0  Female   59000.0   Lagos  15/03/2023
4          105    Michael Lee  35.0    Male   75000.0   Abuja  01/04/2023
5          106   Grace Taylor  26.0  Female   48000.0  Kaduna  12/04/2023
6          107   Daniel White  42.0    Male   95000.0   Lagos  20/04/2023
7          108     Jane Green  30.0  Female   61000.0   Abuja  05/05/2023
8          109    Peter Adams  28.0    Male   55000.0   Lagos  18/05/2023
9          110    Linda Clark  33.0  Female   72000.0  Kaduna  25/05/2023
10         111    Chris Evans  30.0    Male   64000.0   Lagos  01/06/2023
11         112      Anna Hall  25.0  Female   63500.0   Abuja  10/06/2023
12         113    Robert King  39.0    Male   88000.0  Kaduna  15/06/2023
13         114    Emily Stone  32.0  Female   67000.0   Lagos  30/06/2023
14         115     Mark Young  45.0    Male  250000.0   Abuja  05/07/2023
15         116   Susan Wright  29.0  Female   58000.0   Lagos  12/07/2023
16         117    James Scott  34.0    Male   70000.0  Kaduna  20/07/2023
17         118    Helen Baker  27.0  Female   51000.0   Abuja  28/07/2023
18         119    Paul Nelson  41.0    Male   91000.0   Lagos  05/08/2023
19         120  Rachel Carter  30.0  Female   63000.0  Kaduna  15/08/2023
20         120  Rachel Carter  30.0  Female   63000.0  Kaduna  15/08/2023

## Grouping and aggregation

In [54]:
df.groupby('City')['Salary'].sum()

City
Abuja     552500.0
Kaduna    472000.0
Lagos     534000.0
Name: Salary, dtype: float64

### This calculates the total salary per city

In [55]:
df.groupby('City')['Salary'].max()

City
Abuja     250000.0
Kaduna     88000.0
Lagos      95000.0
Name: Salary, dtype: float64

In [59]:
df.groupby('City')['Name'].count()

City
Abuja     6
Kaduna    7
Lagos     8
Name: Name, dtype: int64

In [60]:
df.groupby('Gender')['Salary'].mean()

Gender
Female    59772.727273
Male      90100.000000
Name: Salary, dtype: float64

In [61]:
df.groupby('City')['Salary'].agg(['mean', 'sum', 'min', 'max'])

                mean       sum      min       max
City
Abuja   92083.333333  552500.0  51000.0  250000.0
Kaduna  67428.571429  472000.0  48000.0   88000.0
Lagos   66750.000000  534000.0  45000.0   95000.0