In [2]:
import pandas as pd
import numpy as np

In [ ]:
data = {
    'Name' : ['James Ogah', 'Samuel jin', 'kristof ole', 'John brown', 'benedict patrick',
             'folarin Balogun'],
    'Gender' : ['male', 'Female', 'FEMALE', 'm', 'MALE', ' male'],
    
    'Age' : [20, 21, 30, 'nine', 20, 15],
    'Salary' : [100, 300, 800, 900, 500, 'one'],
    'Performance_Score' : [20, 15, 10, np.nan, 12, 200]   
}

In [7]:
df = pd.DataFrame(data)

In [8]:
print(df)

               Name  Gender   Age Salary  Performance_Score
0        James Ogah    male    20    100               20.0
1        Samuel jin  Female    21    300               15.0
2       kristof ole  FEMALE    30    800               10.0
3        John brown       m  nine    900                NaN
4  benedict patrick    MALE    20    500               12.0
5   folarin Balogun    male    15    one              200.0

In [9]:
df.describe()

       Performance_Score
count           5.000000
mean           51.400000
std            83.155276
min            10.000000
25%            12.000000
50%            15.000000
75%            20.000000
max           200.000000

In [17]:
df.dtypes

Name                     str
Gender                   str
Age                   object
Salary                object
Performance_Score    float64
dtype: object

In [11]:
df.shape

(6, 5)

In [15]:
df['Gender'].unique()

<ArrowStringArray>
['male', 'Female', 'FEMALE', 'm', 'MALE', ' male']
Length: 6, dtype: str

In [16]:
df['Name'].unique()

<ArrowStringArray>
[      'James Ogah',       'Samuel jin',      'kristof ole',
       'John brown', 'benedict patrick',  'folarin Balogun']
Length: 6, dtype: str

In [18]:
df['Age'].unique()

array([20, 21, 30, 'nine', 15], dtype=object)

In [20]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Name               6 non-null      str
 1   Gender             6 non-null      str
 2   Age                6 non-null      object
 3   Salary             6 non-null      object
 4   Performance_Score  5 non-null      float64
dtypes: float64(1), object(2), str(2)
memory usage: 470.0+ bytes

In [23]:
df.head()

               Name  Gender   Age Salary  Performance_Score
0        James Ogah    male    20    100               20.0
1        Samuel jin  Female    21    300               15.0
2       kristof ole  FEMALE    30    800               10.0
3        John brown       m  nine    900                NaN
4  benedict patrick    MALE    20    500               12.0

In [26]:
###Solving numerical inconsistency
df['Age'].dtype

dtype('O')

In [27]:
#Identify the problematic rows
df[pd.to_numeric(df['Age'], errors = 'coerce').isna()]

         Name Gender   Age Salary  Performance_Score
3  John brown      m  nine    900                NaN

In [28]:
#Fix the row
#By replacing the value
df['Age'] = df["Age"].replace({
    'nine' : 9
})

#or

In [30]:
df.head()

               Name  Gender Age Salary  Performance_Score
0        James Ogah    male  20    100               20.0
1        Samuel jin  Female  21    300               15.0
2       kristof ole  FEMALE  30    800               10.0
3        John brown       m   9    900                NaN
4  benedict patrick    MALE  20    500               12.0

In [39]:
#Turning the value to a missing value
pd.to_numeric(df['Age'], errors = 'coerce')

0    20
1    21
2    30
3     9
4    20
5    15
Name: Age, dtype: int64

In [40]:
df['Age'].dtype

dtype('O')

In [45]:
df['Age'].astype(int)

0    20
1    21
2    30
3     9
4    20
5    15
Name: Age, dtype: int64

In [32]:
#Searching for outliers in numerical columns
Q1 = df['Age'].quantile(0.25)
Q3 = df['Age'].quantile(0.75)

IQR = Q3 - Q1
print(IQR)

4.5

In [34]:
lower_limit = Q1 - 1.5 * IQR
higher_limit = Q3 + 1.5 * IQR
print(lower_limit, higher_limit)

9.5 27.5

In [53]:
for index, age in df['Age'].items():
    if (age < 9.5 or age > 27.5):
        print(index)

2
3

In [71]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Name               6 non-null      str
 1   Gender             6 non-null      str
 2   Age                6 non-null      object
 3   Salary             6 non-null      object
 4   Performance_Score  5 non-null      float64
dtypes: float64(1), object(2), str(2)
memory usage: 465.0+ bytes

In [66]:
df.loc[2] = ['John Doe', 'Male', 22, 200, 10]

In [69]:
df.head()

               Name  Gender Age Salary  Performance_Score
0        James Ogah    male  20    100               20.0
1        Samuel jin  Female  21    300               15.0
2          John Doe    Male  22    200               10.0
3        John brown       m   9    900                NaN
4  benedict patrick    MALE  20    500               12.0

In [72]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Name               6 non-null      str
 1   Gender             6 non-null      str
 2   Age                6 non-null      object
 3   Salary             6 non-null      object
 4   Performance_Score  5 non-null      float64
dtypes: float64(1), object(2), str(2)
memory usage: 465.0+ bytes

In [73]:
df.head()

               Name  Gender Age Salary  Performance_Score
0        James Ogah    male  20    100               20.0
1        Samuel jin  Female  21    300               15.0
2          John Doe    Male  22    200               10.0
3        John brown       m   9    900                NaN
4  benedict patrick    MALE  20    500               12.0

17.833333333333332
20.0

In [84]:
df.head()

               Name  Gender Age Salary  Performance_Score
0        James Ogah    male  20    100               20.0
1        Samuel jin  Female  21    300               15.0
2          John Doe    Male  22    200               10.0
3        John brown       m   9    900                NaN
4  benedict patrick    MALE  20    500               12.0

In [86]:
Q1 = df['Performance_Score'].quantile(0.25)
Q3 = df['Performance_Score'].quantile(0.75)

IQR = Q3 - Q1
print(IQR)

8.0

In [87]:
lower_limit = Q1 - 1.5 * IQR
higher_limit = Q3 + 1.5 * IQR
print(lower_limit, higher_limit)

0.0 32.0

In [89]:
for index, score in df['Performance_Score'].items():
    if (score < 0 or score > 32):
        print(score)

200.0

In [90]:
df

               Name  Gender Age Salary  Performance_Score
0        James Ogah    male  20    100               20.0
1        Samuel jin  Female  21    300               15.0
2          John Doe    Male  22    200               10.0
3        John brown       m   9    900                NaN
4  benedict patrick    MALE  20    500               12.0
5   folarin Balogun    male  15    one              200.0

In [94]:
#Removing values and insering another
df.loc[5, 'Salary'] = np.nan
print(df.loc[5])
df.loc[5, 'Performance_Score'] = np.nan
print(df.loc[5])

Name                 folarin Balogun
Gender                          male
Age                               15
Salary                           NaN
Performance_Score              200.0
Name: 5, dtype: object
Name                 folarin Balogun
Gender                          male
Age                               15
Salary                           NaN
Performance_Score                NaN
Name: 5, dtype: object

In [93]:
pmean = df['Performance_Score'].mean()
pmedian = df['Performance_Score'].median()
print(pmean)
print(pmedian)

51.4
15.0

In [95]:
df['Performance_Score'] = df['Performance_Score'].fillna(pmedian)

In [97]:
df.head()

               Name  Gender Age Salary  Performance_Score
0        James Ogah    male  20    100               20.0
1        Samuel jin  Female  21    300               15.0
2          John Doe    Male  22    200               10.0
3        John brown       m   9    900               15.0
4  benedict patrick    MALE  20    500               12.0

In [98]:
#Replacing values
Agemean = df['Age'].mean()
Agemedian = df['Age'].median()
print(Agemean)
print(Agemedian)

17.833333333333332
20.0

In [100]:
#Age Outlier
Q1 = df['Age'].quantile(0.25)
Q3 = df['Age'].quantile(0.75)

IQR = Q3 - Q1
print(IQR)

4.5

In [102]:
lower_limit = Q1 - 1.5 * IQR
higher_limit = Q3 + 1.5 * IQR

print(lower_limit ,higher_limit)

9.5 27.5

In [104]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Name               6 non-null      str
 1   Gender             6 non-null      str
 2   Age                6 non-null      object
 3   Salary             5 non-null      object
 4   Performance_Score  6 non-null      float64
dtypes: float64(1), object(2), str(2)
memory usage: 465.0+ bytes

In [105]:
df['Age']

0    20
1    21
2    22
3     9
4    20
5    15
Name: Age, dtype: object

In [107]:
df['Age'] = pd.to_numeric(df['Age'], errors = 'coerce')

In [108]:
df['Age'].dtype

dtype('int64')

In [110]:
df.loc[df['Age'] < lower_limit, 'Age'] = Agemedian
df.loc[df['Age'] > higher_limit, 'Age'] = Agemedian

In [111]:
df

               Name  Gender  Age Salary  Performance_Score
0        James Ogah    male   20    100               20.0
1        Samuel jin  Female   21    300               15.0
2          John Doe    Male   22    200               10.0
3        John brown       m   20    900               15.0
4  benedict patrick    MALE   20    500               12.0
5   folarin Balogun    male   15    NaN               15.0

In [115]:
salarymean = df['Salary'].mean()
salarymedian = df['Salary'].median()
print(salarymean)
print(salarymedian)

400.0
300.0

In [112]:
#Outliers for salary
Q1 = df['Salary'].quantile(0.25)
Q3 = df['Salary'].quantile(0.75)

IQR = Q3 - Q1
print(IQR)

300.0

In [113]:
lower_limit = Q1 - 1.5 * IQR
higher_limit = Q3 + 1.5 * IQR

print(lower_limit, higher_limit)

-250.0 950.0

In [117]:
df.loc[df['Salary'] < lower_limit, 'Salary'] = df['Salary'].median()
df.loc[df['Salary'] > higher_limit, 'Salary'] = df['Salary'].median()

In [119]:
df['Salary'] = df['Salary'].fillna(salarymedian)

In [120]:
df

               Name  Gender  Age Salary  Performance_Score
0        James Ogah    male   20    100               20.0
1        Samuel jin  Female   21    300               15.0
2          John Doe    Male   22    200               10.0
3        John brown       m   20    900               15.0
4  benedict patrick    MALE   20    500               12.0
5   folarin Balogun    male   15  300.0               15.0

# Cleaning categorical columns
### Name column

In [121]:
df['Name'].str.lower()

0          james ogah
1          samuel jin
2            john doe
3          john brown
4    benedict patrick
5     folarin balogun
Name: Name, dtype: str

In [ ]:
df['Name'].str.title()

In [124]:
df[['First_Name', 'Last_Name']] = df['Name'].str.split(' ', n = 1, expand = True)

In [125]:
df

,Name,Gender,Age,Salary,Performance_Score,First_Name,Last_Name
0,James Ogah,male,20,100,20.0,James,Ogah
1,Samuel jin,Female,21,300,15.0,Samuel,jin
2,John Doe,Male,22,200,10.0,John,Doe
3,John brown,m,20,900,15.0,John,brown
4,benedict patrick,MALE,20,500,12.0,benedict,patrick
5,folarin Balogun,male,15,300.0,15.0,folarin,Balogun

In [126]:
df = df.drop(columns = ['Name'])

In [130]:
col = df.pop('First_Name')
df.insert(0, 'First_Name', col)

In [131]:
df

  First_Name  Gender  Age Salary  Performance_Score Last_Name
0      James    male   20    100               20.0      Ogah
1     Samuel  Female   21    300               15.0       jin
2       John    Male   22    200               10.0       Doe
3       John       m   20    900               15.0     brown
4   benedict    MALE   20    500               12.0   patrick
5    folarin    male   15  300.0               15.0   Balogun

In [132]:
col = df.pop('Last_Name')
df.insert(1, 'Last_Name', col)

In [135]:
df

  First_Name Last_Name  Gender  Age Salary  Performance_Score
0      James      Ogah    male   20    100               20.0
1     Samuel       jin  Female   21    300               15.0
2       John       Doe    Male   22    200               10.0
3       John     brown       m   20    900               15.0
4   benedict   patrick    MALE   20    500               12.0
5    folarin   Balogun    male   15  300.0               15.0

In [136]:
df['First_Name'] = df['First_Name'].str.title()

In [137]:
df['Last_Name'] = df['Last_Name'].str.title()

In [138]:
df

  First_Name Last_Name  Gender  Age Salary  Performance_Score
0      James      Ogah    male   20    100               20.0
1     Samuel       Jin  Female   21    300               15.0
2       John       Doe    Male   22    200               10.0
3       John     Brown       m   20    900               15.0
4   Benedict   Patrick    MALE   20    500               12.0
5    Folarin   Balogun    male   15  300.0               15.0

### Gender Column

In [139]:
df['Gender'] = df['Gender'].str.lower()

In [140]:
df['Gender'] = df['Gender'].str.title()

In [141]:
df

  First_Name Last_Name  Gender  Age Salary  Performance_Score
0      James      Ogah    Male   20    100               20.0
1     Samuel       Jin  Female   21    300               15.0
2       John       Doe    Male   22    200               10.0
3       John     Brown       M   20    900               15.0
4   Benedict   Patrick    Male   20    500               12.0
5    Folarin   Balogun    Male   15  300.0               15.0

In [144]:
for index, row in df.iterrows():
    if (row['Gender'] != 'Male' and row['Gender'] != 'Female'):
        print(row)

First_Name            John
Last_Name            Brown
Gender                   M
Age                     20
Salary                 900
Performance_Score     15.0
Name: 3, dtype: object
First_Name           Folarin
Last_Name            Balogun
Gender                  Male
Age                       15
Salary                 300.0
Performance_Score       15.0
Name: 5, dtype: object

In [145]:
df['Gender'] = df['Gender'].replace({
    'M' : 'Male'
})

In [146]:
df['Gender']

0      Male
1    Female
2      Male
3      Male
4      Male
5      Male
Name: Gender, dtype: str

In [147]:
df['Gender'].unique()

<ArrowStringArray>
['Male', 'Female', ' Male']
Length: 3, dtype: str

In [148]:
df

  First_Name Last_Name  Gender  Age Salary  Performance_Score
0      James      Ogah    Male   20    100               20.0
1     Samuel       Jin  Female   21    300               15.0
2       John       Doe    Male   22    200               10.0
3       John     Brown    Male   20    900               15.0
4   Benedict   Patrick    Male   20    500               12.0
5    Folarin   Balogun    Male   15  300.0               15.0