In [2]:
import pandas as pd
import numpy as np

In [3]:
dataframe = pd.read_csv("Penguin Species Prediction Dataset.csv")

In [4]:
df = dataframe.copy()

In [5]:
df.head()

,species,island,culmen_length_mm,culmen_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,41.1,18.4,195.0,3886.0,Female
1,Gentoo,Biscoe,50.0,15.4,217.0,4303.0,Male
2,Gentoo,Biscoe,50.0,15.1,220.0,4954.0,Female
3,Chinstrap,Dream,48.7,19.0,196.0,3739.0,Male
4,Adelie,Dream,39.0,17.8,187.0,3607.0,Male

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   species            1000 non-null   str
 1   island             1000 non-null   str
 2   culmen_length_mm   990 non-null    float64
 3   culmen_depth_mm    990 non-null    float64
 4   flipper_length_mm  990 non-null    float64
 5   body_mass_g        990 non-null    float64
 6   sex                990 non-null    str
dtypes: float64(4), str(3)
memory usage: 72.1 KB

In [7]:
df.isnull().sum()

species               0
island                0
culmen_length_mm     10
culmen_depth_mm      10
flipper_length_mm    10
body_mass_g          10
sex                  10
dtype: int64

In [8]:
df.duplicated().sum()

np.int64(0)

In [9]:
df['species'].unique()

<ArrowStringArray>
['Adelie', 'Gentoo', 'Chinstrap']
Length: 3, dtype: str

In [10]:
df['island'].unique()

<ArrowStringArray>
['Torgersen', 'Biscoe', 'Dream']
Length: 3, dtype: str

In [11]:
df['culmen_length_mm'].isnull().sum()

np.int64(10)

In [12]:
# Outlier function
def find_outlier(df, column):
    Q1 = df[column].quantile(0.25)
    Q3 = df[column].quantile(0.75)

    IQR = Q3 - Q1

    lower_limit = Q1 - 1.5 * IQR
    higher_limit = Q3 + 1.5 * IQR

    return lower_limit, higher_limit

In [13]:
culmenLengthOutlier = find_outlier(df, 'culmen_length_mm')
print(culmenLengthOutlier)

(np.float64(25.050000000000004), np.float64(62.24999999999999))

In [14]:
cllower_limit = 25.050000000000004
clhigher_limit = 62.24999999999999

for index, row in df.iterrows():
    if(row['culmen_length_mm'] < cllower_limit or row['culmen_length_mm'] > clhigher_limit):
        print(row)

In [15]:
clmean = df['culmen_length_mm'].mean()
clmedian = df['culmen_length_mm'].median()
print(clmean)
print(clmedian)

43.817777777777785
43.8

In [16]:
df['culmen_length_mm'] = df['culmen_length_mm'].fillna(clmedian)

In [17]:
df['culmen_length_mm'].isnull().sum()

np.int64(0)

In [18]:
df.head()

,species,island,culmen_length_mm,culmen_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,41.1,18.4,195.0,3886.0,Female
1,Gentoo,Biscoe,50.0,15.4,217.0,4303.0,Male
2,Gentoo,Biscoe,50.0,15.1,220.0,4954.0,Female
3,Chinstrap,Dream,48.7,19.0,196.0,3739.0,Male
4,Adelie,Dream,39.0,17.8,187.0,3607.0,Male

In [19]:
#culmen_depth_mm
cdoutliers = find_outlier(df, 'culmen_depth_mm')
print(cdoutliers)

(np.float64(11.450000000000003), np.float64(23.049999999999997))

In [20]:
cdlower_limit = 11.450000000000003
cdhigher_limit = 23.049999999999997
for index, row in df.iterrows():
    if(row['culmen_depth_mm'] < cdlower_limit or row['culmen_depth_mm'] > cdhigher_limit):
        print(row)

In [21]:
cdmean = df['culmen_depth_mm'].mean()
cdmedian = df['culmen_depth_mm'].median()
print(cdmean)
print(cdmedian)

17.335555555555555
17.8

In [22]:
df['culmen_depth_mm'] = df['culmen_depth_mm'].fillna(cdmedian)

In [23]:
df['culmen_depth_mm'].isnull().sum()

np.int64(0)

In [24]:
df.head()

,species,island,culmen_length_mm,culmen_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,41.1,18.4,195.0,3886.0,Female
1,Gentoo,Biscoe,50.0,15.4,217.0,4303.0,Male
2,Gentoo,Biscoe,50.0,15.1,220.0,4954.0,Female
3,Chinstrap,Dream,48.7,19.0,196.0,3739.0,Male
4,Adelie,Dream,39.0,17.8,187.0,3607.0,Male

In [25]:
#flipper_length_mm
df['flipper_length_mm'].isnull().sum()

np.int64(10)

In [26]:
floutlier = find_outlier(df, 'flipper_length_mm')
print(floutlier)

(np.float64(154.5), np.float64(246.5))

In [27]:
fl_lowerlimit = 154.5
fl_higherlimit = 246.5
for index, row in df.iterrows():
    if (row['flipper_length_mm'] < fl_lowerlimit or row['flipper_length_mm'] > fl_higherlimit):
        print(row)

In [28]:
flmean = df['flipper_length_mm'].mean()
flmedian = df['flipper_length_mm'].median()
print(flmean)
print(flmedian)

199.22424242424242
195.0

In [29]:
df['flipper_length_mm'] = df['flipper_length_mm'].fillna(flmedian)

In [30]:
df['flipper_length_mm'].isnull().sum()

np.int64(0)

In [31]:
df.head()

,species,island,culmen_length_mm,culmen_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,41.1,18.4,195.0,3886.0,Female
1,Gentoo,Biscoe,50.0,15.4,217.0,4303.0,Male
2,Gentoo,Biscoe,50.0,15.1,220.0,4954.0,Female
3,Chinstrap,Dream,48.7,19.0,196.0,3739.0,Male
4,Adelie,Dream,39.0,17.8,187.0,3607.0,Male

In [32]:
df['body_mass_g'].isnull().sum()

np.int64(10)

In [33]:
bmoutliers = find_outlier(df, 'body_mass_g')
print(bmoutliers)

(np.float64(2084.5), np.float64(6088.5))

In [34]:
bmlower_limit = 2084.5
bmhigher_limit = 6088.5

for index, row in df.iterrows():
    if(row['body_mass_g'] < bmlower_limit or row['body_mass_g'] > bmhigher_limit):
        print(row)

species              Gentoo
island               Biscoe
culmen_length_mm       43.3
culmen_depth_mm        13.7
flipper_length_mm     223.0
body_mass_g          6148.0
sex                  Female
Name: 74, dtype: object
species              Gentoo
island               Biscoe
culmen_length_mm       49.5
culmen_depth_mm        14.8
flipper_length_mm     223.0
body_mass_g          6114.0
sex                    Male
Name: 325, dtype: object
species              Gentoo
island               Biscoe
culmen_length_mm       48.3
culmen_depth_mm        14.0
flipper_length_mm     215.0
body_mass_g          6258.0
sex                  Female
Name: 395, dtype: object
species              Gentoo
island               Biscoe
culmen_length_mm       50.8
culmen_depth_mm        16.2
flipper_length_mm     216.0
body_mass_g          6176.0
sex                    Male
Name: 618, dtype: object
species              Gentoo
island               Biscoe
culmen_length_mm       50.3
culmen_depth_mm        14.7
flipper_length_mm     221.0
body_mass_g          6317.0
sex                    Male
Name: 631, dtype: object
species              Gentoo
island               Biscoe
culmen_length_mm       43.8
culmen_depth_mm        14.7
flipper_length_mm     216.0
body_mass_g          6237.0
sex                    Male
Name: 748, dtype: object

In [35]:
bmmean = df['body_mass_g'].mean()
bmmedian = df['body_mass_g'].median()
print(bmmean)
print(bmmedian)

4103.311111111111
3882.0

In [36]:
df['body_mass_g'] = df['body_mass_g'].fillna(bmmedian)

In [37]:
df['body_mass_g'].isnull().sum()

np.int64(0)

In [38]:
df.head()

,species,island,culmen_length_mm,culmen_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,41.1,18.4,195.0,3886.0,Female
1,Gentoo,Biscoe,50.0,15.4,217.0,4303.0,Male
2,Gentoo,Biscoe,50.0,15.1,220.0,4954.0,Female
3,Chinstrap,Dream,48.7,19.0,196.0,3739.0,Male
4,Adelie,Dream,39.0,17.8,187.0,3607.0,Male

In [39]:
df['sex'].isnull().sum()

np.int64(10)

In [40]:
df['sex'].value_counts()

sex
Male      528
Female    462
Name: count, dtype: int64

In [41]:
df['sex'].mode()

0    Male
Name: sex, dtype: str

In [42]:
df['sex'] = df['sex'].fillna(df['sex'].mode)

In [43]:
df.head()

,species,island,culmen_length_mm,culmen_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,41.1,18.4,195.0,3886.0,Female
1,Gentoo,Biscoe,50.0,15.4,217.0,4303.0,Male
2,Gentoo,Biscoe,50.0,15.1,220.0,4954.0,Female
3,Chinstrap,Dream,48.7,19.0,196.0,3739.0,Male
4,Adelie,Dream,39.0,17.8,187.0,3607.0,Male

In [44]:
df.isnull().sum()

species              0
island               0
culmen_length_mm     0
culmen_depth_mm      0
flipper_length_mm    0
body_mass_g          0
sex                  0
dtype: int64

In [45]:
df.groupby('species')['culmen_length_mm'].min()

species
Adelie       32.4
Chinstrap    40.9
Gentoo       38.2
Name: culmen_length_mm, dtype: float64

In [46]:
df.groupby('species')['culmen_length_mm'].max()

species
Adelie       44.8
Chinstrap    56.0
Gentoo       54.0
Name: culmen_length_mm, dtype: float64

In [47]:
df.groupby(['species', 'island']).agg({
    'culmen_length_mm' : ['max', 'min'],
    'culmen_depth_mm' : ['max', 'min']
})

                    culmen_length_mm       culmen_depth_mm
                                 max   min             max   min
species   island
Adelie    Biscoe                42.3  34.0            19.1  16.2
          Dream                 44.8  32.4            20.6  15.6
          Torgersen             44.6  32.8            21.4  15.8
Chinstrap Dream                 56.0  40.9            20.9  15.8
Gentoo    Biscoe                54.0  38.2            17.8  13.0

In [48]:
df.corr(numeric_only = True)

,culmen_length_mm,culmen_depth_mm,flipper_length_mm,body_mass_g
culmen_length_mm,1.000000,-0.341261,0.496126,0.368560
culmen_depth_mm,-0.341261,1.000000,-0.741732,-0.735260
flipper_length_mm,0.496126,-0.741732,1.000000,0.747758
body_mass_g,0.368560,-0.735260,0.747758,1.000000

### The best correlation is between body_mass_g and flipper_length_mm

## Save the cleaned dataset

In [50]:
df.to_csv('Cleaned Penguin specie.csv', index = False)