In [34]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

## Inspection

In [35]:
data = pd.read_csv('ENGLAND-Football-Dataset.csv')

df = data.copy()

In [36]:
df.head()

,tournament,home,home_goal,away_goal,away,home_corner,away_corner,home_attack,away_attack,home_shots,away_shots,time,date,ht_diff,at_diff,ht_result,at_result,total_corners
0,Premier League,Newcastle,0.0,0.0,Leicester,0.0,0.0,NaN,NaN,NaN,NaN,20:00:00,2023-05-22,0.0,0.0,DRAW,DRAW,0.0
1,Premier League,Man City,0.0,0.0,Chelsea,0.0,0.0,NaN,NaN,NaN,NaN,16:00:00,2023-05-21,0.0,0.0,DRAW,DRAW,0.0
2,Premier League,Brighton,0.0,0.0,Southampton,0.0,0.0,NaN,NaN,NaN,NaN,14:00:00,2023-05-21,0.0,0.0,DRAW,DRAW,0.0
3,Premier League,West Ham,0.0,0.0,Leeds,0.0,0.0,NaN,NaN,NaN,NaN,13:30:00,2023-05-21,0.0,0.0,DRAW,DRAW,0.0
4,Premier League,Nottm Forest,0.0,0.0,Arsenal,0.0,0.0,NaN,NaN,NaN,NaN,17:30:00,2023-05-20,0.0,0.0,DRAW,DRAW,0.0

In [37]:
df.shape

(21894, 18)

In [38]:
df.isnull().sum()

tournament          0
home                0
home_goal           0
away_goal           0
away                0
home_corner         0
away_corner         0
home_attack      4624
away_attack      4624
home_shots       4583
away_shots       4595
time                0
date                0
ht_diff             0
at_diff             0
ht_result           0
at_result           0
total_corners       0
dtype: int64

In [39]:
df.dtypes

tournament           str
home                 str
home_goal        float64
away_goal        float64
away                 str
home_corner      float64
away_corner      float64
home_attack      float64
away_attack      float64
home_shots       float64
away_shots       float64
time                 str
date                 str
ht_diff          float64
at_diff          float64
ht_result            str
at_result            str
total_corners    float64
dtype: object

## Cleaning

In [40]:
## Tournament
df['tournament'].unique()

<ArrowStringArray>
[         'Premier League',    'England Championship',
        'England League 1',        'England League 2',
 'England National League']
Length: 5, dtype: str

## Filtering this dataset by tournament

In [41]:
Prem_games = df[df['tournament'] == 'Premier League']
Championship = df[df['tournament'] == 'England Championship']
League1 = df[df['tournament'] ==  'England League 1']
League2 = df[df['tournament'] == 'England League 2']
National_league = df[df['tournament'] == 'England National League']
Prem_games

,tournament,home,home_goal,away_goal,away,home_corner,away_corner,home_attack,away_attack,home_shots,away_shots,time,date,ht_diff,at_diff,ht_result,at_result,total_corners
0,Premier League,Newcastle,0.0,0.0,Leicester,0.0,0.0,NaN,NaN,NaN,NaN,20:00:00,2023-05-22,0.0,0.0,DRAW,DRAW,0.0
1,Premier League,Man City,0.0,0.0,Chelsea,0.0,0.0,NaN,NaN,NaN,NaN,16:00:00,2023-05-21,0.0,0.0,DRAW,DRAW,0.0
2,Premier League,Brighton,0.0,0.0,Southampton,0.0,0.0,NaN,NaN,NaN,NaN,14:00:00,2023-05-21,0.0,0.0,DRAW,DRAW,0.0
3,Premier League,West Ham,0.0,0.0,Leeds,0.0,0.0,NaN,NaN,NaN,NaN,13:30:00,2023-05-21,0.0,0.0,DRAW,DRAW,0.0
4,Premier League,Nottm Forest,0.0,0.0,Arsenal,0.0,0.0,NaN,NaN,NaN,NaN,17:30:00,2023-05-20,0.0,0.0,DRAW,DRAW,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3381,Premier League,Newcastle,0.0,3.0,Sunderland,7.0,3.0,NaN,NaN,NaN,NaN,12:45:00,2014-02-01,-3.0,3.0,LOST,WON,10.0
3382,Premier League,Stoke,3.0,5.0,Liverpool,10.0,2.0,NaN,NaN,NaN,NaN,16:10:00,2014-01-12,-2.0,2.0,LOST,WON,12.0
3383,Premier League,Fulham,1.0,4.0,Sunderland,10.0,5.0,NaN,NaN,NaN,NaN,15:00:00,2014-01-11,-3.0,3.0,LOST,WON,15.0
3384,Premier League,Stoke,1.0,0.0,Everton,1.0,5.0,NaN,NaN,NaN,NaN,15:00:00,2014-01-01,1.0,-1.0,WON,LOST,6.0
3385,Premier League,Liverpool,2.0,0.0,Hull,3.0,4.0,NaN,NaN,NaN,NaN,15:00:00,2014-01-01,2.0,-2.0,WON,LOST,7.0

In [66]:
### Function to find outrageous numbers to look at
def find_outliers(df, column):
    Q1 = df[column].quantile(0.25)
    Q3 = df[column].quantile(0.75)

    IQR = Q3 - Q1

    lower_limit = Q1 - 1.5 * IQR
    higher_limit = Q3 + 1.5 * IQR

    return lower_limit, higher_limit

In [67]:
Prem_games.isnull().sum()

tournament         0
home               0
home_goal          0
away_goal          0
away               0
home_corner        0
away_corner        0
home_attack      793
away_attack      792
home_shots       794
away_shots       794
time               0
date               0
ht_diff            0
at_diff            0
ht_result          0
at_result          0
total_corners      0
dtype: int64

In [68]:
Prem_games['home'].nunique()

33

In [69]:
Prem_games['away'].nunique()

33

### A total of 33 distinct teams playing as of the time recorded

In [70]:
Prem_games[Prem_games['home'].isna()]

Empty DataFrame
Columns: [tournament, home, home_goal, away_goal, away, home_corner, away_corner, home_attack, away_attack, home_shots, away_shots, time, date, ht_diff, at_diff, ht_result, at_result, total_corners]
Index: []

In [93]:
drawprem_games_corners = Prem_games[(Prem_games['home_goal'] == 0) & (Prem_games['away_goal'] == 0)
    & (Prem_games['home_corner'] == 0) & (Prem_games['away_corner'] == 0)]
drawprem_games_corners

,tournament,home,home_goal,away_goal,away,home_corner,away_corner,home_attack,away_attack,home_shots,away_shots,time,date,ht_diff,at_diff,ht_result,at_result,total_corners
0,Premier League,Newcastle,0.0,0.0,Leicester,0.0,0.0,NaN,NaN,NaN,NaN,20:00:00,2023-05-22,0.0,0.0,DRAW,DRAW,0.0
1,Premier League,Man City,0.0,0.0,Chelsea,0.0,0.0,NaN,NaN,NaN,NaN,16:00:00,2023-05-21,0.0,0.0,DRAW,DRAW,0.0
2,Premier League,Brighton,0.0,0.0,Southampton,0.0,0.0,NaN,NaN,NaN,NaN,14:00:00,2023-05-21,0.0,0.0,DRAW,DRAW,0.0
3,Premier League,West Ham,0.0,0.0,Leeds,0.0,0.0,NaN,NaN,NaN,NaN,13:30:00,2023-05-21,0.0,0.0,DRAW,DRAW,0.0
4,Premier League,Nottm Forest,0.0,0.0,Arsenal,0.0,0.0,NaN,NaN,NaN,NaN,17:30:00,2023-05-20,0.0,0.0,DRAW,DRAW,0.0
5,Premier League,Bournemouth,0.0,0.0,Man Utd,0.0,0.0,NaN,NaN,NaN,NaN,15:00:00,2023-05-20,0.0,0.0,DRAW,DRAW,0.0
6,Premier League,Fulham,0.0,0.0,Crystal Palace,0.0,0.0,NaN,NaN,NaN,NaN,15:00:00,2023-05-20,0.0,0.0,DRAW,DRAW,0.0
7,Premier League,Liverpool,0.0,0.0,Aston Villa,0.0,0.0,NaN,NaN,NaN,NaN,15:00:00,2023-05-20,0.0,0.0,DRAW,DRAW,0.0
8,Premier League,Wolverhampton,0.0,0.0,Everton,0.0,0.0,NaN,NaN,NaN,NaN,15:00:00,2023-05-20,0.0,0.0,DRAW,DRAW,0.0
9,Premier League,Tottenham,0.0,0.0,Brentford,0.0,0.0,NaN,NaN,NaN,NaN,12:30:00,2023-05-20,0.0,0.0,DRAW,DRAW,0.0
10,Premier League,Newcastle,0.0,0.0,Brighton,0.0,0.0,NaN,NaN,NaN,NaN,19:30:00,2023-05-18,0.0,0.0,DRAW,DRAW,0.0
2485,Premier League,Southampton,0.0,0.0,Everton,0.0,0.0,120.0,114.0,16.0,10.0,16:30:00,2016-11-27,0.0,0.0,DRAW,DRAW,0.0

### We can agree that the the games can end as a draw but it's highly unlikely that both teams will finish a game without playing corners and having attacking stats so we can fill it by using the mean or median of the columns

In [82]:
premhomecornermean = Prem_games['home_corner'].mean()
premhomecornermedian = Prem_games['home_corner'].median()
premawaycornermean = Prem_games['away_corner'].mean()
premawaycornermedian = Prem_games['away_corner'].median()

print(f'The average home corners in the prem is {premhomecornermean}')
print(f'The median home corners in the prem is {premhomecornermedian}')
print(f'The average away corners in the prem is {premawaycornermean}')
print(f'The median away corners in the prem is {premawaycornermedian}')

The average home corners in the prem is 5.713821618428825
The median home corners in the prem is 5.0
The average away corners in the prem is 4.671293561724749
The median away corners in the prem is 4.0

In [89]:
drawprem_games_corners['home_corner'] = drawprem_games_corners['home_corner'].replace({
    0.0 : premhomecornermedian
})

KeyError: 'home_corner'

In [90]:
type(drawprem_games_corners)

pandas.Series

In [91]:
type(Prem_games)

pandas.DataFrame